### PR TITLE
Coordinator stopped on bad control command

### LINKED ISSUE #648: coordinator crashes on bad logs access
**Describe the bug**

When I try to view logs using `dora logs`, the coordinator crashes if I input incorrect information (e.g., an invalid UUID or name). The same happens when there is an error, such as a wrong node ID or when multiple dataflows have the same name.

**Environment (please complete the following information):**
- System: macOS
- Dora version: tag v0.3.6

### PR DESCRIPTION
**Pull request by Hennzau**
Fix #648 and more

### CODE REVIEW

File: binaries/coordinator/src/lib.rs [hunk 1]
```diff
@@ -663,17 +658,17 @@ struct DaemonConnection {
...
     daemon_events_tx: &mut Option<mpsc::Sender<Event>>,
     clock: &HLC,
 ) -> Result<(), eyre::ErrReport> {
     abortable_events.abort();
-    for (&uuid, dataflow) in running_dataflows {
-        stop_dataflow(
-            dataflow,
-            uuid,
+    for dataflow_uuid in running_dataflows.keys().cloned().collect::<Vec<_>>() {
+        let _ = stop_dataflow(
```
Comment (haixuanTao) [inline binaries/coordinator/src/lib.rs:669]: Do we really need to change the stop_dataflow return type if we are not using it?

**Review by haixuanTao — APPROVED** [review]
Looks good overall :)

Thanks!

File: binaries/coordinator/src/lib.rs (hunk 1 above)
Comment (Hennzau) [reply binaries/coordinator/src/lib.rs:669]: We are using it in the control loop for `dora stop` but not for the `dora destroy` command. But its more readable if we don't have 2 different functions to do that.
```rust
let dataflow = stop_dataflow(
    &mut running_dataflows,
    dataflow_uuid,
    &mut daemon_connections,
    clock.new_timestamp(),
    grace_duration,
)
.await;

match dataflow {
    Ok(dataflow) => {
        dataflow.reply_senders.push(reply_sender);
    }
    Err(err) => {
        let _ = reply_sender.send(Err(err));
    }
}
```
