### PR TITLE
CLI: Improve error messages when coordinator is not running

### LINKED ISSUE #250: The dora service is not started. An error is reported execute dora list
**Describe the bug**
The dora service is not started. An error is reported execute dora list

**To Reproduce**
1. dora list

**Screenshots or Video**
QQ20230414-201905

**Environments (please complete the following information):**
 - System info: `Linux jia 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Dora version : 0.2.2

### PR DESCRIPTION
**Pull request by phil-opp**
This PR improves the reported errors when the CLI fails to connect to dora daemon. Instead of a "connection refused" error, we now output a "could not connect to dora coordinator" error.

Fixes #250

### CODE REVIEW

File: binaries/cli/src/up.rs [hunk 1]
```diff
@@ -17,34 +13,44 @@ pub(crate) fn up(
...
+    match connect_to_coordinator() {
+        Ok(mut session) => {
+            // send destroy command to dora-coordinator
+            session
+                .request(&serde_json::to_vec(&ControlRequest::Destroy).unwrap())
+                .wrap_err("failed to send destroy message")?;
+            println!("Send destroy command to dora-coordinator");
+        }
+        Err(_) => {
+            eprintln!("The dora-coordinator does not seem to be running");
```
Comment (haixuanTao) [inline binaries/cli/src/up.rs:52]: As we plan to make the `dora-coordinator` available for multiple machine I think it might be more lasting to say that:
```
we could not connect to the `dora-coordinator`
```
Meaning its an I/O issue rather than a process issue that can be misguided.

File: binaries/cli/src/up.rs [hunk 2]
```diff
@@ -17,34 +13,44 @@ pub(crate) fn up(
...
 
-    if !coordinator_running()? {
-        start_coordinator(coordinator).wrap_err("failed to start dora-coordinator")?;
-        // sleep a bit until the coordinator accepts connections
-        while !coordinator_running()? {
-            std::thread::sleep(Duration::from_millis(50));
+    let mut session = match connect_to_coordinator() {
+        Ok(session) => session,
+        Err(_) => {
+            start_coordinator(coordinator).wrap_err("failed to start dora-coordinator")?;
```
Comment (haixuanTao) [inline binaries/cli/src/up.rs:19]: I'm not a fan of spawning a coordinator if we failed to connect to the coordinator. What if the dora-coordinator should be on a different machine? 

I think its ok to fail the request if the coordinator is not reachable.

Comment (phil-opp) [reply binaries/cli/src/up.rs:19]: We only do this for the `dora up` command, which I imagine will be mostly used for local testing.

File: binaries/cli/src/up.rs (hunk 1 above)
Comment (phil-opp) [reply binaries/cli/src/up.rs:52]: Agreed!

File: binaries/cli/src/up.rs (hunk 2 above)
Comment (haixuanTao) [reply binaries/cli/src/up.rs:19]: Right, I thought it was on all connections sorry!

I still feel like if there is a need to run `up` two times to get the `dora-coordinator up`, it should not be a feature and there should be an investigation. What if the first spawning worked but we did not reach it and end up somehow with two coordinator.

File: binaries/cli/src/check.rs [hunk 3]
```diff
@@ -16,19 +17,30 @@ pub fn check_environment() -> eyre::Result<()> {
...
-        error_occured = true;
-    }
+    let mut session = match connect_to_coordinator() {
+        Ok(session) => {
+            let _ = stdout.set_color(ColorSpec::new().set_fg(Some(Color::Green)));
+            writeln!(stdout, "ok")?;
+            Some(session)
+        }
+        Err(_) => {
+            let _ = stdout.set_color(ColorSpec::new().set_fg(Some(Color::Red)));
```
Comment (haixuanTao) [inline binaries/cli/src/check.rs:27]: I feel like we're re-implementing something in the likes of: https://docs.rs/color-eyre/latest/color_eyre/

Comment (phil-opp) [reply binaries/cli/src/check.rs:27]: This is just for coloring the status of the coordinator and deamon in the output. For example: 
image

So compared to `color_eyre`, it isnot directly related to error handling,

File: binaries/cli/src/up.rs (hunk 2 above)
Comment (phil-opp) [reply binaries/cli/src/up.rs:19]: Are you talking about the "failed to start dora-coordinator" error?

File: binaries/cli/src/check.rs (hunk 3 above)
Comment (haixuanTao) [reply binaries/cli/src/check.rs:27]: Ah yeah okay. In that case, we can live it as is.

File: binaries/cli/src/up.rs (hunk 2 above)
Comment (haixuanTao) [reply binaries/cli/src/up.rs:19]: I misread the file, the first time, and I was spooked by the spawn on `Err(_)`, but I misunderstood it at a failure of spawning a first time.

But, I still think that we should not `start_coordinator` on failing to connect to the coordinator. Let say there is an internet connection issue and we fail to connect to the coordinator. That will makes us try to spawn a new coordinator.

I think that the design pattern `Err(_) => Spawn` might create even more error. I would prefer to try spawning the coordinator without trying to connect to the coordinator and raise an error on the port being already taken or an error of the kind.

This seems to be more natural and more common when spawning servers. 

But open for discussion

Comment (phil-opp) [reply binaries/cli/src/up.rs:19]: > I would prefer to try spawning the coordinator without trying to connect to the coordinator and raise an error on the port being already taken or an error of the kind.

I'm generally fine with this approach as well, but unfortunately this would be a breaking change. Right now, you can run `dora up` multiple times without errors. So I think it's best to leave the behavior as is for now and revisit this once we're planning version 0.3.0. If you like we can create some sort of tracking issue for the 0.3.0 release so that we don't forget about it.

Comment (phil-opp) [reply binaries/cli/src/up.rs:19]: It's worth noting that the same applies to the `dora check` command. Right now, the command assumes a local setup and performs the same logic for checking the coordinator and daemon setup. So we might want to redesign this command too once we have support for distributed deployments (see #256).

Comment (haixuanTao) [reply binaries/cli/src/up.rs:19]: That is true, that it is a breaking change. Make sense to keep it as it is then

**Review by haixuanTao — APPROVED** [review]
